# Ce fichier doit être à la RACINE de votre dépôt

[build]
  # 1. Indique à Netlify d'abord faire "cd project"
  base = "project"
  
  # 2. Indique où trouver les fonctions (relatif à "base")
  functions = "netlify/functions"